version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: "gateway"
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
#      - TZ=Europe/Moscow

  server:
    restart: on-failure
    build: ./server
    container_name: "server"
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_NAME=shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=6541
#      - TZ=Europe/Moscow

  db:
    image: postgres:14.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: "db"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - TZ=Europe/Moscow